openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Вход пользователя (логин)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
                password: { type: string }
      responses:
        '200':
          description: OK (токен)
        '401':
          description: Unauthorized
  /auth/register:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
                password: { type: string }
                role: { type: string }
      responses:
        '201':
          description: Created
        '400':
          description: Already exists
components:
  schemas:
    User:
      type: object
      properties:
        id: { type: integer }
        username: { type: string }
        role: { type: string }
